server:
  port: 8082
spring:
  application:
    name: order-service   # ✅ updated name to reflect Order Service
  datasource:
    url: jdbc:mysql://192.168.23.141:3306/order-micro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Creative2089!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://192.168.23.141:8761/eureka   # ✅ include /eureka for correctness
    register-with-eureka: true
    fetch-registry: true
