server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-micro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "@Dmin2089!"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    ROOT: INFO
    com.techforu.user: DEBUG
